using System;

public struct RoundResult : IEquatable<RoundResult>
{
    //NOWAY PUBLIC FIELDS
    //Wait a minute... Sir, they are readonly
    public readonly int Score;
    public readonly RoundOutcome Outcome;

    //Generated by ide
    public RoundResult(int score, RoundOutcome outcome)
    {
        Score = score;
        Outcome = outcome;
    }

    public bool Equals(RoundResult other)
    {
        return Score == other.Score && Outcome == other.Outcome;
    }

    public override bool Equals(object obj)
    {
        return obj is RoundResult other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(Score, (int)Outcome);
    }
}